version: "3.7"
services:
  db:
    image: postgres:14.2-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - custom
networks:
  custom:
    driver: bridge
volumes:
  db:
    driver: local