version: "3.7"
services:
  crypto_alfred:
    image: luchanos/crypto_alfred:1.0.6
    env_file:
      - .env
    ports:
      - "5433:5433"
    networks:
      - custom
  postgres_db:
    image: postgres:14.2-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - custom
  mongo_db:
    image: mongo
    container_name: "mongo_db"
    ports:
      - "27017-27019:27017-27019"
    environment:
      - MONGO_INITDB_DATABASE=crypto_alfred_db
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo_db:/var/lib/mongodb/data
    networks:
      - custom
networks:
  custom:
    driver: bridge
volumes:
  postgres_db:
    driver: local
  mongo_db:
    driver: local
